image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
  key: pip

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - test -n "$SKIP_PIP_INSTALL" || find .wheels -name '*.whl' -print0 | xargs -0 --no-run-if-empty pip --require-virtualenv install
  - test -n "$SKIP_PIP_INSTALL" || pip --require-virtualenv install -r requirements_dev.txt

stages:
  - prepare
  - lint
  - test
  - sonarqube-check

build-ldap:
  stage: prepare
  variables:
    SKIP_PIP_INSTALL: "yes"
  script:
  - apt update && apt install -y libldap-dev python3-dev libsasl2-dev
  - pip install python-ldap
  - mkdir .wheels
  - find .cache/pip -name 'python_ldap*.whl' -print0 | xargs -0 -i cp -v "{}" .wheels/
  artifacts:
    expire_in: 2 days
    paths:
    - .wheels

test:
  script:
    - printf "[run]\nconcurrency = multiprocessing" > .coveragerc
    - coverage run ./manage.py test --parallel
    - coverage combine
    - coverage xml
  artifacts:
    expire_in: 2 days
    paths:
      - coverage.xml

migrations-check:
  stage: test
  script:
    - ./manage.py makemigrations --no-input --check -v0 ||
      ( RET=$?; echo "makemigrations failed with code $?, dry-run follows:" 1>&2;
        ./manage.py makemigrations --no-input --dry-run; exit $RET )

black:
  stage: lint
  script:
    - black . --check

isort:
  stage: lint
  script:
    - isort . --check

mypy:
  stage: lint
  script:
    - mypy .

sonarqube-check:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - ''
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.host.url=${CI_SONAR_HOST} -Dsonar.token=${CI_SONAR_TOKEN}
  allow_failure: true
  needs:
    - job: test
      artifacts: true
