variables:
  UV_VERSION: "0.12.1"
  PYTHON_VERSION: "3.10"
  BASE_LAYER: trixie
  UV_LINK_MODE: copy
  UV_CACHE_DIR: .uv-cache
  runStages: prepare lint test analyse

image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER

cache:
  key:
    files:
      - uv.lock
  paths:
    - $UV_CACHE_DIR

before_script:
  - python -V
  - |
    if [ -f "$UV_CACHE_DIR/.uv-cache-ready" ]; then
      echo "Skipping apt install"
    else
      apt update && apt install -y libldap-dev python3-dev libsasl2-dev
      mkdir -p "$UV_CACHE_DIR"
      touch "$UV_CACHE_DIR/.uv-cache-ready"
    fi
  - uv sync --frozen

after_script:
  - uv cache prune --ci

stages:
  - prepare
  - lint
  - test
  - docs
  - analyse

prepare-cache:
  stage: prepare
  script:
    - uv tree

test:
  script:
    - printf "[run]\nconcurrency = multiprocessing" > .coveragerc
    - uv run coverage run ./manage.py test --parallel
    - uv run coverage combine
    - uv run coverage xml
  artifacts:
    expire_in: 2 days
    paths:
      - coverage.xml
  rules:
    - if: $runStages =~ /(test|sonarqube-check)/
      when: always

migrations-check:
  stage: test
  script:
    - uv run ./manage.py makemigrations --no-input --check -v0 ||
      ( RET=$?; echo "makemigrations failed with code $?, dry-run follows:" 1>&2;
        ./manage.py makemigrations --no-input --dry-run; exit $RET )
  rules:
    - if: $runStages =~ /test/
      when: always

black:
  stage: lint
  script:
    - uv run black . --check
  rules:
    - if: $runStages =~ /lint/
      when: always

flake8:
  stage: lint
  script:
    - uv run flake8
  rules:
    - if: $runStages =~ /lint/
      when: always

isort:
  stage: lint
  script:
    - uv run isort . --check
  rules:
    - if: $runStages =~ /lint/
      when: always

mypy:
  stage: lint
  script:
    - uv run mypy .
  rules:
    - if: $runStages =~ /lint/
      when: always

sonarqube-check:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - ''
  script:
    - >
      sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.host.url=${CI_SONAR_HOST}
      -Dsonar.token=${CI_SONAR_TOKEN}
  allow_failure: true
  needs:
    - job: test
      artifacts: true
  rules:
    - if: $runStages =~ /analyse/
      when: always

uv-audit:
  stage: analyse
  script:
    - uv audit
  allow_failure: true
  rules:
    - if: $runStages =~ /analyse/
      when: always

pages:
  stage: docs
  script:
    - uv run make -C docs html
    - mv docs/_build/html public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

pages-test:
  stage: docs
  script:
    - uv run make -C docs html
    - mv docs/_build/html test
  artifacts:
    expire_in: 1 week
    paths:
      - test
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
