# Generated by Django 4.2.9 on 2024-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="notification_email_address",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Notification email address"),
        ),
        migrations.AddField(
            model_name="role",
            name="notification_language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                default="en",
                max_length=2,
                verbose_name="Notification language",
            ),
        ),
    ]
