# Generated by Django 4.2.15 on 2024-11-04 14:42

from django.db import migrations, models

import kamu.validators.identity


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0002_role_notification_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=models.CharField(
                max_length=20,
                validators=[kamu.validators.identity.PhoneNumberValidator()],
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[kamu.validators.identity.PhoneNumberValidator()],
                verbose_name="Phone number",
            ),
        ),
    ]
