# Generated by Django 4.2.16 on 2024-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0003_alter_phonenumber_number_alter_token_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="type",
            field=models.CharField(
                choices=[("account", "User account"), ("generic", "Generic permission"), ("service", "Service")],
                default="generic",
                max_length=10,
                verbose_name="Permission type",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="value",
            field=models.CharField(blank=True, max_length=4000, verbose_name="Permission value"),
        ),
    ]
