# Generated by Django 4.2.16 on 2025-01-08 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0004_permission_type_permission_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("account", "Account"), ("lightaccount", "Light Account")],
                        default="lightaccount",
                        max_length=15,
                        verbose_name="Account type",
                    ),
                ),
                ("uid", models.CharField(max_length=255, verbose_name="User ID")),
                ("deactivated_at", models.DateTimeField(blank=True, null=True, verbose_name="Deactivated at")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="useraccount", to="kamu.identity"
                    ),
                ),
            ],
            options={
                "verbose_name": "User account",
                "verbose_name_plural": "User accounts",
            },
        ),
        migrations.CreateModel(
            name="AccountSynchronization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number_of_failures", models.IntegerField(default=0, verbose_name="Number of failures")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kamu.account")),
            ],
            options={
                "verbose_name": "Account synchronization",
                "verbose_name_plural": "Account synchronizations",
            },
        ),
    ]
