# Generated by Django 4.2.20 on 2025-05-13 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0006_alter_accountsynchronization_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="organisation_unit",
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=20, unique=True, verbose_name="Organisation identifier")),
                ("abbreviation", models.CharField(max_length=20, verbose_name="Organisation abbreviation")),
                ("name_fi", models.CharField(max_length=255, verbose_name="Organisation name (fi)")),
                ("name_en", models.CharField(max_length=255, verbose_name="Organisation name (en)")),
                ("name_sv", models.CharField(max_length=255, verbose_name="Organisation name (sv)")),
                ("code", models.CharField(max_length=50, verbose_name="Organisation code")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kamu.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kamu.organisation",
                verbose_name="Organisation unit",
            ),
        ),
    ]
