# Generated by Django 4.2.20 on 2025-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0007_remove_role_organisation_unit_organisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identifier",
            name="name",
            field=models.CharField(blank=True, max_length=256, verbose_name="Identifier name"),
        ),
    ]
