# Generated by Django 4.2.20 on 2025-06-06 06:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0008_identifier_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="identifier",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for this membership.",
                null=True,
                verbose_name="Membership ID",
            ),
        ),
    ]
