# Generated by Django 4.2.20 on 2025-06-06 06:39

import uuid

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def gen_uuid(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Membership = apps.get_model("kamu", "Membership")
    for row in Membership.objects.all():
        row.identifier = uuid.uuid4()
        row.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0009_add_membership_identifier"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
