# Generated by Django 4.2.20 on 2025-06-06 06:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0010_populate_membership_identifier_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="identifier",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for this membership.",
                unique=True,
                verbose_name="Membership ID",
            ),
        ),
    ]
