# Generated by Django 4.2.22 on 2025-06-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0011_remove_membership_identifier_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="useraccount", to="kamu.identity"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="kamu.contracttemplate"),
        ),
    ]
