# Generated by Django 4.2.22 on 2025-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0012_alter_account_identity_alter_contract_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="invite_language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                default="en",
                max_length=2,
                verbose_name="Invite language",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="invite_text",
            field=models.TextField(
                blank=True,
                help_text="This replaces beginning of the default invite message. Lines of the invite text are "
                "wrapped to 70 characters. Invite code and link will be added to end of the message. Use preview to "
                "see the final result.",
                verbose_name="Invite text",
            ),
        ),
    ]
