# Generated by Django 4.2.22 on 2025-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0013_membership_invite_language_membership_invite_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancelled at"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("require", "Missing requirements"),
                    ("approval", "Waiting approval"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=10,
                verbose_name="Membership status",
            ),
        ),
    ]
