# Generated by Django 4.2.22 on 2025-06-27 10:59

from django.db import migrations, models

import kamu.validators.identity


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0014_membership_cancelled_at_alter_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="verify_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number to send the verification SMS to. In international format, e.g. +358123456789.",
                max_length=20,
                validators=[kamu.validators.identity.PhoneNumberValidator()],
                verbose_name="Verify phone number",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="require_sms_verification",
            field=models.BooleanField(default=False, verbose_name="Requires SMS verification"),
        ),
    ]
