# Generated by Django 4.2.22 on 2025-08-28 12:03

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils import timezone


def migrate_verified_to_datetime(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:

    for mdl in ["emailaddress", "identifier", "phonenumber"]:
        my_model = apps.get_model("kamu", mdl)

        for mm in my_model.objects.all():

            if mm.verified_old:
                mm.verified = timezone.now()
                mm.save()


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0015_membership_verify_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailaddress",
            options={
                "ordering": ["identity", "priority"],
                "verbose_name": "Email address",
                "verbose_name_plural": "Email addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="phonenumber",
            options={
                "ordering": ["identity", "priority"],
                "verbose_name": "Phone number",
                "verbose_name_plural": "Phone numbers",
            },
        ),
        migrations.RenameField(
            model_name="emailaddress",
            old_name="verified",
            new_name="verified_old",
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="verified",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Verified at"),
        ),
        migrations.RenameField(
            model_name="identifier",
            old_name="verified",
            new_name="verified_old",
        ),
        migrations.AddField(
            model_name="identifier",
            name="verified",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Verified at"),
        ),
        migrations.RenameField(
            model_name="phonenumber",
            old_name="verified",
            new_name="verified_old",
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="verified",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Verified at"),
        ),
        migrations.RunPython(migrate_verified_to_datetime),
        migrations.RemoveField(
            model_name="emailaddress",
            name="verified_old",
        ),
        migrations.RemoveField(
            model_name="identifier",
            name="verified_old",
        ),
        migrations.RemoveField(
            model_name="phonenumber",
            name="verified_old",
        ),
    ]
