# Generated by Django 4.2.22 on 2025-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0016_alter_emailaddress_options_alter_phonenumber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsynchronization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[("enabled", "Enabled"), ("expired", "Expired"), ("disabled", "Disabled")],
                default="enabled",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
