# Generated by Django 4.2.25 on 2025-10-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0017_accountsynchronization_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttemplate",
            name="name_en",
            field=models.CharField(max_length=200, verbose_name="Contract name (en)"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="name_fi",
            field=models.CharField(max_length=200, verbose_name="Contract name (fi)"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="name_sv",
            field=models.CharField(max_length=200, verbose_name="Contract name (sv)"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="type",
            field=models.CharField(max_length=50, verbose_name="Contract type"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="description_en",
            field=models.TextField(verbose_name="Permission description (en)"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="description_fi",
            field=models.TextField(verbose_name="Permission description (fi)"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="description_sv",
            field=models.TextField(verbose_name="Permission description (sv)"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="identifier",
            field=models.CharField(max_length=50, unique=True, verbose_name="Permission identifier"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name_en",
            field=models.CharField(max_length=200, verbose_name="Permission name (en)"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name_fi",
            field=models.CharField(max_length=200, verbose_name="Permission name (fi)"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name_sv",
            field=models.CharField(max_length=200, verbose_name="Permission name (sv)"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="name_en",
            field=models.CharField(max_length=200, verbose_name="Requirement name (en)"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="name_fi",
            field=models.CharField(max_length=200, verbose_name="Requirement name (fi)"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="name_sv",
            field=models.CharField(max_length=200, verbose_name="Requirement name (sv)"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_en",
            field=models.TextField(verbose_name="Role description (en)"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_fi",
            field=models.TextField(verbose_name="Role description (fi)"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_sv",
            field=models.TextField(verbose_name="Role description (sv)"),
        ),
        migrations.AlterField(
            model_name="role",
            name="identifier",
            field=models.CharField(max_length=50, unique=True, verbose_name="Role identifier"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name_en",
            field=models.CharField(max_length=200, verbose_name="Role name (en)"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name_fi",
            field=models.CharField(max_length=200, verbose_name="Role name (fi)"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name_sv",
            field=models.CharField(max_length=200, verbose_name="Role name (sv)"),
        ),
    ]
