# Generated by Django 4.2.25 on 2025-10-24 09:10

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def migrate_nationality(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:

    identity_model = apps.get_model("kamu", "identity")
    nationality_model = apps.get_model("kamu", "nationality")

    for identity in identity_model.objects.all():
        nationality_verification = identity.nationality_verification
        for nationality in identity.nationality.all():
            nationality_model.objects.get_or_create(
                identity=identity, country=nationality, defaults={"verification_method": nationality_verification}
            )


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0018_alter_contracttemplate_name_en_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Nationality",
            new_name="Country",
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "verification_method",
                    models.SmallIntegerField(
                        choices=[
                            (0, "No verification"),
                            (1, "Self assurance"),
                            (2, "External source"),
                            (3, "Verified with a government issued photo-ID"),
                            (4, "Strong electrical verification"),
                        ],
                        default=0,
                        verbose_name="Verification method",
                    ),
                ),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kamu.country")),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nationalities", to="kamu.identity"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={"verbose_name": "Nationality", "verbose_name_plural": "Nationalities"},
        ),
        migrations.RunPython(migrate_nationality),
        migrations.AddConstraint(
            model_name="nationality",
            constraint=models.UniqueConstraint(fields=("identity", "country"), name="unique_identity_country"),
        ),
        migrations.RemoveField(
            model_name="identity",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="nationality_verification",
        ),
        migrations.AddField(
            model_name="identity",
            name="gender_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified with a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Gender verification method",
            ),
        ),
    ]
