# Generated by Django 4.2.25 on 2025-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0019_alter_nationality_add_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identifier",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Valid until"),
        ),
        migrations.AddField(
            model_name="identity",
            name="candour_verification_session_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Candour session ID"),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("fpic", "Finnish personal identity code"),
                    ("eidas", "eIDAS identifier"),
                    ("eppn", "eduPersonPrincipalName"),
                    ("google", "Google account"),
                    ("microsoft", "Microsoft account"),
                    ("kamu", "Kamu identifier"),
                    ("person", "Person identifier"),
                    ("id", "Government issued ID"),
                    ("other", "Other identifier"),
                ],
                max_length=10,
                verbose_name="Identifier type",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="assurance_level",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No assurance level"),
                    (1, "Low, self-asserted with a verified email-address"),
                    (2, "Medium, verified with a government issued photo-ID"),
                    (3, "High, eIDAS substantial level or similar"),
                    (4, "Highest, eIDAS high level or similar"),
                ],
                default=0,
                help_text="How strongly this user identity is identified.",
                verbose_name="Assurance level",
            ),
        ),
    ]
