# Generated by Django 5.2.8 on 2025-11-10 06:35

import uuid

from django.db import migrations

import kamu.models.shared


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0020_identifier_valid_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="kamu_id",
            field=kamu.models.shared.Char32UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for this identity.",
                unique=True,
                verbose_name="Kamu ID",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="identifier",
            field=kamu.models.shared.Char32UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for this membership.",
                unique=True,
                verbose_name="Membership ID",
            ),
        ),
    ]
