# Generated by Django 5.2.9 on 2025-12-03 14:10

from django.db import migrations, models

import kamu.validators.identity


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0021_alter_identity_kamu_id_alter_membership_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("account", "Account"), ("lightaccount", "Limited user account")],
                default="lightaccount",
                max_length=15,
                verbose_name="Account type",
            ),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("fpic", "Finnish personal identity code"),
                    ("eidas", "eIDAS identifier"),
                    ("eppn", "User identifier from organisation"),
                    ("google", "Google account"),
                    ("microsoft", "Microsoft account"),
                    ("kamu", "Kamu identifier"),
                    ("person", "Person identifier"),
                    ("id", "Government issued ID"),
                    ("other", "Other identifier"),
                ],
                max_length=10,
                verbose_name="Identifier type",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="assurance_level",
            field=models.SmallIntegerField(
                choices=[(0, "No verification"), (1, "Low"), (2, "Medium"), (3, "High"), (4, "Very high")],
                default=0,
                help_text="How strongly this user identity is identified.",
                verbose_name="Assurance level",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other"), ("U", "")],
                default="U",
                help_text="Required for the user identification from the official identity documents.",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="given_name_display",
            field=models.CharField(
                blank=True,
                help_text="Preferred name, i.e. one of the official given names or, for a justified reason, another "
                "given name. Please note that this information is usually displayed in applications.",
                max_length=200,
                verbose_name="Preferred given name",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="given_names",
            field=models.CharField(
                blank=True,
                help_text="All official given names, as on a passport. Please note that this information is usually "
                "not displayed in applications.",
                max_length=200,
                verbose_name="Official given names",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="surname",
            field=models.CharField(
                blank=True,
                help_text="All official surname(s), as on a passport. Please note that this information is usually "
                "not displayed in applications.",
                max_length=200,
                verbose_name="Surname",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="surname_display",
            field=models.CharField(
                blank=True,
                help_text="As a rule, the official last name or, for a justified reason, part thereof. Please note "
                "that this information is usually displayed in applications.",
                max_length=200,
                verbose_name="Preferred surname",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                default="en",
                max_length=2,
                verbose_name="Possible default email invitation replacement text",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_text",
            field=models.TextField(
                blank=True,
                help_text="If you wish, you can replace the beginning part of the default email invite with your own "
                "text (max. 70 characters). The invitation code and link are always added at the end of the "
                "message. Preview the message to see the finished email.",
                verbose_name="Invite text",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="reason",
            field=models.TextField(verbose_name="Reasons for membership"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="verify_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number to which the confirmation SMS will be sent, in the international format, e.g. "
                "+358123456789.",
                max_length=20,
                validators=[kamu.validators.identity.PhoneNumberValidator()],
                verbose_name="Verify phone number",
            ),
        ),
    ]
