# Generated by Django 5.2.9 on 2026-01-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0022_alter_identity_given_name_display_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identity",
            options={
                "permissions": [
                    ("view_basic_information", "Can view basic information"),
                    ("change_basic_information", "Can change basic information"),
                    ("view_restricted_information", "Can view restricted information"),
                    ("change_restricted_information", "Can change restricted information"),
                    ("view_contacts", "Can view contact information"),
                    ("change_contacts", "Can change contact information"),
                    ("view_contracts", "Can view contract information"),
                    ("view_identifiers", "Can view identifiers"),
                    ("change_identifiers", "Can change identifiers"),
                    ("search_identities", "Can search identities"),
                    ("combine_identities", "Can combine identities"),
                    ("view_authentication_settings", "Can view authentication settings"),
                    ("change_assurance_level", "Can change assurance level for identity"),
                    ("change_single_contact_auth", "Can change single contact authentication for identity"),
                    ("change_unverified_contact_auth", "Can change unverified contact authentication for identity"),
                ],
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
            },
        ),
        migrations.AddField(
            model_name="identity",
            name="allow_auth_with_single_contact",
            field=models.BooleanField(default=False, verbose_name="Allow login with single contact"),
        ),
        migrations.AddField(
            model_name="identity",
            name="allow_auth_with_unverified_contact",
            field=models.BooleanField(default=False, verbose_name="Allow login with unverified contact"),
        ),
    ]
