# Generated by Django 5.2.9 on 2026-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0023_alter_identity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="invite_given_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Given name"),
        ),
        migrations.AddField(
            model_name="membership",
            name="invite_surname",
            field=models.CharField(blank=True, max_length=200, verbose_name="Surname"),
        ),
    ]
