# Generated by Django 5.2.11 on 2026-02-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0024_membership_invite_given_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="invite_text",
            field=models.TextField(
                blank=True,
                help_text="If you wish, you can replace the beginning part of the default email invite with your own "
                "text. The invitation code and link are always added at the end of the message. Preview the message "
                "to see the finished email.",
                verbose_name="Invite text",
            ),
        ),
    ]
