# Generated by Django 5.2.11 on 2026-02-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0025_alter_membership_invite_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["role__identifier", "expire_date"],
                "permissions": [
                    ("view_memberships", "Can view membership details"),
                    ("approve_memberships", "Can approve all memberships"),
                    ("invite_memberships", "Can invite to all roles"),
                ],
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
    ]
