# Generated by Django 5.2.11 on 2026-03-03 13:20

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def map_verification_level(old_level: int) -> int:
    if old_level == 0:
        return 0
    elif old_level == 1:
        return 10
    elif old_level == 2:
        return 20
    elif old_level == 3:
        return 40
    elif old_level == 4:
        return 50
    else:
        return old_level


def map_assurance_level(old_level: int) -> int:
    if old_level == 0:
        return 0
    elif old_level == 1:
        return 10
    elif old_level == 2:
        return 20
    elif old_level == 3:
        return 30
    elif old_level == 4:
        return 40
    else:
        return old_level


def migrate_verification_levels(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:

    identity_model = apps.get_model("kamu", "identity")
    nationality_model = apps.get_model("kamu", "nationality")

    for identity in identity_model.objects.all():
        changed = False
        for field in [
            "date_of_birth_verification",
            "fpic_verification",
            "gender_verification",
            "given_names_verification",
            "surname_verification",
        ]:
            old_level = getattr(identity, field)
            new_level = map_verification_level(old_level)
            if new_level != old_level:
                changed = True
                setattr(identity, field, new_level)
        old_assurance_level = getattr(identity, "assurance_level")
        new_assurance_level = map_assurance_level(old_assurance_level)
        if new_assurance_level != old_assurance_level:
            changed = True
            setattr(identity, "assurance_level", new_assurance_level)
        if changed:
            identity.save()

    for nationality in nationality_model.objects.all():
        old_level = getattr(nationality, "verification_method")
        new_level = map_verification_level(old_level)
        if new_level != old_level:
            setattr(nationality, "verification_method", new_level)
            nationality.save()


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0026_alter_membership_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="assurance_level",
            field=models.SmallIntegerField(
                choices=[(0, "No verification"), (10, "Low"), (20, "Medium"), (30, "High"), (40, "Very high")],
                default=0,
                help_text="How strongly this user identity is identified.",
                verbose_name="Assurance level",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="date_of_birth_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (10, "Self assurance"),
                    (20, "External source"),
                    (30, "User verified"),
                    (40, "Verified with a government issued photo-ID"),
                    (50, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Date of birth verification method",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="fpic_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (10, "Self assurance"),
                    (20, "External source"),
                    (30, "User verified"),
                    (40, "Verified with a government issued photo-ID"),
                    (50, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="FPIC verification method",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="gender_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (10, "Self assurance"),
                    (20, "External source"),
                    (30, "User verified"),
                    (40, "Verified with a government issued photo-ID"),
                    (50, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Gender verification method",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="given_names_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (10, "Self assurance"),
                    (20, "External source"),
                    (30, "User verified"),
                    (40, "Verified with a government issued photo-ID"),
                    (50, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Given names verification method",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="surname_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (10, "Self assurance"),
                    (20, "External source"),
                    (30, "User verified"),
                    (40, "Verified with a government issued photo-ID"),
                    (50, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Surname verification method",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="verification_method",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (10, "Self assurance"),
                    (20, "External source"),
                    (30, "User verified"),
                    (40, "Verified with a government issued photo-ID"),
                    (50, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Verification method",
            ),
        ),
        migrations.RunPython(migrate_verification_levels),
    ]
