# Generated by Django 5.2.11 on 2026-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0027_alter_identity_assurance_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="level",
            field=models.IntegerField(
                default=0,
                help_text="Require a minimum level of assurance or attribute verification level, or a minimum version "
                "of contract. Contract level must be a positive integer. Assurance levels are from 10 (low) to 40 "
                "(highest) and attribute verification levels are from 10 (self assured) to 50 (strong electrical "
                "verification)",
                verbose_name="Level or version required",
            ),
        ),
    ]
