# Generated by Django 5.2.11 on 2026-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0028_alter_requirement_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "permissions": [
                    ("view_accounts", "Can view account information"),
                    ("change_accounts", "Can change account information"),
                    ("lock_accounts", "Can lock and unlock accounts"),
                ],
                "verbose_name": "User account",
                "verbose_name_plural": "User accounts",
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("expired", "Expired"),
                    ("disabled", "Disabled"),
                    ("locked", "Locked"),
                ],
                default="enabled",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
