# Generated by Django 5.2.13 on 2026-05-18 13:10

from django.db import migrations, models

import kamu.validators.identity


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0029_alter_account_options_alter_account_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="invite_given_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Given name of the person being invited"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                default="en",
                max_length=2,
                verbose_name="The language used to communicate with the invited person",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_surname",
            field=models.CharField(blank=True, max_length=200, verbose_name="Surname of the person being invited"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_text",
            field=models.TextField(
                blank=True,
                help_text="If you wish, you can replace the beginning part of the default email invite with your own "
                "text. The invitation code and link are always added at the end of the message. Preview the message "
                "to see the finished email.",
                verbose_name="Alternative text for the default email invitation",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="verify_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number to which the confirmation SMS will be sent, in the international format, e.g. "
                "+358123456789.",
                max_length=20,
                validators=[kamu.validators.identity.PhoneNumberValidator()],
                verbose_name="Invite mobile phone number",
            ),
        ),
    ]
