# Generated by Django 5.2.13 on 2026-06-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kamu", "0030_alter_membership_invite_given_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="identity",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="kamu.identity"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="kamu.role"),
        ),
    ]
