# Generated by Django 4.2.5 on 2023-09-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("role", "0001_initial"),
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="roles",
            field=models.ManyToManyField(through="role.Membership", to="role.role"),
        ),
        migrations.AddField(
            model_name="identity",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
