# Generated by Django 4.2.5 on 2023-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_attributetype_alter_identity_user_attribute"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attributetype",
            old_name="name",
            new_name="identifier",
        ),
        migrations.AddField(
            model_name="attributetype",
            name="description_en",
            field=models.CharField(default="en", max_length=255, verbose_name="Attribute description (en)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attributetype",
            name="description_fi",
            field=models.CharField(default="fi", max_length=255, verbose_name="Attribute description (fi)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attributetype",
            name="description_sv",
            field=models.CharField(default="sv", max_length=255, verbose_name="Attribute description (sv)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attributetype",
            name="name_en",
            field=models.CharField(default="en", max_length=20, verbose_name="Attribute name (en)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attributetype",
            name="name_fi",
            field=models.CharField(default="fi", max_length=20, verbose_name="Attribute name (fi)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attributetype",
            name="name_sv",
            field=models.CharField(default="sv", max_length=20, verbose_name="Attribute name (sv)"),
            preserve_default=False,
        ),
    ]
