# Generated by Django 4.2.5 on 2023-10-30 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_add_attributetype_name_fields_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"verbose_name": "Attribute", "verbose_name_plural": "Attributes"},
        ),
        migrations.AlterModelOptions(
            name="attributetype",
            options={"verbose_name": "Attribute type", "verbose_name_plural": "Attribute types"},
        ),
        migrations.AlterModelOptions(
            name="identity",
            options={"verbose_name": "Identity", "verbose_name_plural": "Identities"},
        ),
        migrations.AddField(
            model_name="attribute",
            name="priority",
            field=models.SmallIntegerField(default=0, verbose_name="Attribute priority"),
        ),
        migrations.AddField(
            model_name="identity",
            name="external",
            field=models.BooleanField(default=False, verbose_name="External identity"),
        ),
        migrations.AddField(
            model_name="identity",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Display name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attributetype",
            name="identifier",
            field=models.CharField(max_length=20, unique=True, verbose_name="Attribute identifier"),
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hetu", "Finnish national identification number"),
                            ("eidas", "eIDAS identifier"),
                            ("eppn", "eduPersonPrincipalName"),
                            ("google", "Google account"),
                            ("microsoft", "Microsoft account"),
                        ],
                        max_length=10,
                        verbose_name="Identifier type",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Identifier value")),
                ("validated", models.BooleanField(default=False, verbose_name="Validated")),
                ("deactivated_at", models.DateTimeField(blank=True, null=True, verbose_name="Deactivated at")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="identifiers", to="identity.identity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Identifier",
                "verbose_name_plural": "Identifiers",
            },
        ),
    ]
