# Generated by Django 4.2.5 on 2023-11-10 10:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0005_alter_attribute_options_alter_attributetype_options_and_more"),
        ("role", "0005_remove_permission_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "address",
                    models.CharField(
                        max_length=320,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email address",
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0, verbose_name="Priority")),
                ("verified", models.BooleanField(default=False, verbose_name="Verified")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={
                "verbose_name": "E-mail address",
                "verbose_name_plural": "E-mail addresses",
            },
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=20, verbose_name="Phone number")),
                ("priority", models.SmallIntegerField(default=0, verbose_name="Priority")),
                ("verified", models.BooleanField(default=False, verbose_name="Verified")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={
                "verbose_name": "Phone number",
                "verbose_name_plural": "Phone numbers",
            },
        ),
        migrations.RemoveField(
            model_name="identifier",
            name="validated",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="name",
        ),
        migrations.AddField(
            model_name="identifier",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
        migrations.AddField(
            model_name="identity",
            name="assurance_level",
            field=models.CharField(
                choices=[
                    ("none", "No assurance level"),
                    ("low", "Low, self-asserted with a verified email-address"),
                    ("medium", "Medium, verified from a government issued photo-ID"),
                    ("high", "High, eIDAS substantial level or similar"),
                ],
                default="none",
                max_length=10,
                verbose_name="Assurance level",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.AddField(
            model_name="identity",
            name="date_of_birth_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Date of birth verification method",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="gender_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Gender verification method",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="given_names",
            field=models.CharField(blank=True, max_length=255, verbose_name="Given names"),
        ),
        migrations.AddField(
            model_name="identity",
            name="given_names_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Given names verification method",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="nationality",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nationality"),
        ),
        migrations.AddField(
            model_name="identity",
            name="nationality_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Nationality verification method",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="nickname",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nickname"),
        ),
        migrations.AddField(
            model_name="identity",
            name="nickname_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Nickname verification method",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                default="en",
                max_length=2,
                verbose_name="Preferred language",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="surname",
            field=models.CharField(blank=True, max_length=255, verbose_name="Surname"),
        ),
        migrations.AddField(
            model_name="identity",
            name="surname_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="Surname verification method",
            ),
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
        migrations.DeleteModel(
            name="AttributeType",
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="phone_numbers", to="identity.identity"
            ),
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="email_addresses", to="identity.identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="phonenumber",
            constraint=models.UniqueConstraint(fields=("identity", "number"), name="unique_phone_number"),
        ),
        migrations.AddConstraint(
            model_name="emailaddress",
            constraint=models.UniqueConstraint(fields=("identity", "address"), name="unique_email_address"),
        ),
    ]
