# Generated by Django 4.2.5 on 2023-11-23 11:43

import django.utils.timezone
from django.db import migrations, models

import identity.validators


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0006_emailaddress_phonenumber_remove_identifier_validated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=2, unique=True, verbose_name="Country code")),
                ("name_fi", models.CharField(max_length=100, verbose_name="Country name (fi)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Country name (en)")),
                ("name_sv", models.CharField(max_length=100, verbose_name="Country name (sv)")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={
                "verbose_name": "Nationality",
                "verbose_name_plural": "Nationalities",
            },
        ),
        migrations.AlterModelOptions(
            name="identity",
            options={
                "permissions": [
                    ("view_basic_information", "Can view basic information"),
                    ("change_basic_information", "Can change basic information"),
                    ("view_restricted_information", "Can view restricted information"),
                    ("change_restricted_information", "Can change restricted information"),
                    ("view_contacts", "Can view contact information"),
                    ("change_contacts", "Can change contact information"),
                    ("view_identifiers", "Can view identifiers"),
                    ("change_identifiers", "Can change identifiers"),
                ],
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
            },
        ),
        migrations.RemoveField(
            model_name="identity",
            name="gender_verification",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="nickname_verification",
        ),
        migrations.AddField(
            model_name="identity",
            name="fpic",
            field=models.CharField(
                blank=True,
                help_text="Used for the strong electrical identification.",
                max_length=11,
                validators=[identity.validators.FpicValidator()],
                verbose_name="Finnish personal identity code",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="fpic_verification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No verification"),
                    (1, "Self assurance"),
                    (2, "External source"),
                    (3, "Verified from a government issued photo-ID"),
                    (4, "Strong electrical verification"),
                ],
                default=0,
                verbose_name="FPIC verification method",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="given_name_display",
            field=models.CharField(
                blank=True,
                help_text="A given name or nickname part of the user's display name.",
                max_length=200,
                verbose_name="Displayed given name",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="surname_display",
            field=models.CharField(
                blank=True,
                help_text="A surname part of the user's display name.",
                max_length=200,
                verbose_name="Displayed surname",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="uid",
            field=models.CharField(
                blank=True,
                help_text="University of Helsinki user account name.",
                max_length=11,
                verbose_name="HY user account name",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="assurance_level",
            field=models.CharField(
                choices=[
                    ("none", "No assurance level"),
                    ("low", "Low, self-asserted with a verified email-address"),
                    ("medium", "Medium, verified from a government issued photo-ID"),
                    ("high", "High, eIDAS substantial level or similar"),
                ],
                default="none",
                help_text="How strongly this user identity is identified.",
                max_length=10,
                verbose_name="Assurance level",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Required for the user identification from the official identity documents.",
                null=True,
                verbose_name="Date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="external",
            field=models.BooleanField(
                default=False,
                help_text="This identity is managed in another registry.",
                verbose_name="External identity",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other"), ("U", "Unknown")],
                default="U",
                help_text="Used for statistical purposes.",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="given_names",
            field=models.CharField(
                blank=True, help_text="All official first names.", max_length=200, verbose_name="Given names"
            ),
        ),
        migrations.RemoveField(
            model_name="identity",
            name="nationality",
        ),
        migrations.AlterField(
            model_name="identity",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Finnish"), ("sv", "Swedish")],
                default="en",
                help_text="Preferred service language.",
                max_length=2,
                verbose_name="Preferred language",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="surname",
            field=models.CharField(
                blank=True, help_text="Official surname(s).", max_length=200, verbose_name="Surname"
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="nationality",
            field=models.ManyToManyField(
                help_text="Required for the user identification from the official identity documents.",
                to="identity.nationality",
            ),
        ),
    ]
