# Generated by Django 4.2.5 on 2024-01-10 13:17

from uuid import uuid4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0007_nationality_alter_identity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="kamu_id",
            field=models.UUIDField(
                default=uuid4,
                help_text="Unique identifier for this identity.",
                null=True,
                verbose_name="Kamu ID",
            ),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("hetu", "Finnish national identification number"),
                    ("eidas", "eIDAS identifier"),
                    ("eppn", "eduPersonPrincipalName"),
                    ("google", "Google account"),
                    ("microsoft", "Microsoft account"),
                    ("kamu", "Kamu identifier"),
                ],
                max_length=10,
                verbose_name="Identifier type",
            ),
        ),
    ]
