# Generated by Django 4.2.5 on 2024-01-10 13:25

from uuid import uuid4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_identity_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="kamu_id",
            field=models.UUIDField(
                default=uuid4,
                help_text="Unique identifier for this identity.",
                unique=True,
                verbose_name="Kamu ID",
            ),
        ),
    ]
