# Generated by Django 4.2.5 on 2024-01-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0010_identity_kamu_id_remove_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("fpic", "Finnish national identification number"),
                    ("eidas", "eIDAS identifier"),
                    ("eppn", "eduPersonPrincipalName"),
                    ("google", "Google account"),
                    ("microsoft", "Microsoft account"),
                    ("kamu", "Kamu identifier"),
                ],
                max_length=10,
                verbose_name="Identifier type",
            ),
        ),
    ]
