# Generated by Django 4.2.5 on 2024-01-25 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0012_alter_identity_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checksum", models.CharField(max_length=64, verbose_name="Checksum")),
                ("lang", models.CharField(max_length=2, verbose_name="Language")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=20, verbose_name="Contract type")),
                ("version", models.SmallIntegerField(verbose_name="Contract version")),
                ("name_fi", models.CharField(max_length=100, verbose_name="Contract name (fi)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Contract name (en)")),
                ("name_sv", models.CharField(max_length=100, verbose_name="Contract name (sv)")),
                ("text_fi", models.TextField(verbose_name="Contract text (fi)")),
                ("text_en", models.TextField(verbose_name="Contract text (en)")),
                ("text_sv", models.TextField(verbose_name="Contract text (sv)")),
                ("public", models.BooleanField(default=False, verbose_name="Public")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "Contract template",
                "verbose_name_plural": "Contract templates",
            },
        ),
        migrations.AlterModelOptions(
            name="identity",
            options={
                "permissions": [
                    ("view_basic_information", "Can view basic information"),
                    ("change_basic_information", "Can change basic information"),
                    ("view_restricted_information", "Can view restricted information"),
                    ("change_restricted_information", "Can change restricted information"),
                    ("view_contacts", "Can view contact information"),
                    ("change_contacts", "Can change contact information"),
                    ("view_contracts", "Can view contract information"),
                    ("view_identifiers", "Can view identifiers"),
                    ("change_identifiers", "Can change identifiers"),
                    ("search_identities", "Can search identities"),
                ],
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
            },
        ),
        migrations.AddConstraint(
            model_name="contracttemplate",
            constraint=models.UniqueConstraint(fields=("type", "version"), name="unique_contract_template"),
        ),
        migrations.AddField(
            model_name="contract",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contracts", to="identity.identity"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="identity.contracttemplate"),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(fields=("identity", "template"), name="unique_contract"),
        ),
    ]
