# Generated by Django 4.2.9 on 2024-01-30 15:19

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

import identity.validators


def set_empty_values_null(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    identity = apps.get_model("identity", "Identity")
    for row in identity.objects.all():
        if row.fpic == "":
            row.fpic = None
        if row.uid == "":
            row.uid = None
        row.save(update_fields=["fpic", "uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0013_contract_contracttemplate_alter_identity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="fpic",
            field=models.CharField(
                blank=True,
                help_text="Used for the strong electrical identification.",
                max_length=11,
                null=True,
                validators=[identity.validators.FpicValidator()],
                verbose_name="Finnish personal identity code",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="uid",
            field=models.CharField(
                blank=True,
                help_text="University of Helsinki user account name.",
                max_length=11,
                null=True,
                verbose_name="HY user account name",
            ),
        ),
        migrations.RunPython(set_empty_values_null),
        migrations.AlterField(
            model_name="identity",
            name="fpic",
            field=models.CharField(
                blank=True,
                help_text="Used for the strong electrical identification.",
                max_length=11,
                null=True,
                unique=True,
                validators=[identity.validators.FpicValidator()],
                verbose_name="Finnish personal identity code",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="uid",
            field=models.CharField(
                blank=True,
                help_text="University of Helsinki user account name.",
                max_length=11,
                null=True,
                unique=True,
                verbose_name="HY user account name",
            ),
        ),
    ]
