# Generated by Django 4.2.9 on 2024-02-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0015_alter_identity_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailaddress",
            options={
                "ordering": ["identity", "verified", "priority"],
                "verbose_name": "E-mail address",
                "verbose_name_plural": "E-mail addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="phonenumber",
            options={
                "ordering": ["identity", "verified", "priority"],
                "verbose_name": "Phone number",
                "verbose_name_plural": "Phone numbers",
            },
        ),
    ]
