# Generated by Django 4.2.9 on 2024-02-07 10:44

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_assurance_levels(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    identity = apps.get_model("identity", "Identity")
    for row in identity.objects.all():
        if row.assurance_level == "high":
            row.assurance_level = "3"
        elif row.assurance_level == "medium":
            row.assurance_level = "2"
        elif row.assurance_level == "low":
            row.assurance_level = "1"
        else:
            row.assurance_level = "0"
        row.save(update_fields=["assurance_level"])


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0016_alter_emailaddress_options_alter_phonenumber_options"),
    ]

    operations = [
        migrations.RunPython(set_assurance_levels),
        migrations.AlterField(
            model_name="identity",
            name="assurance_level",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No assurance level"),
                    (1, "Low, self-asserted with a verified email-address"),
                    (2, "Medium, verified from a government issued photo-ID"),
                    (3, "High, eIDAS substantial level or similar"),
                ],
                default=0,
                help_text="How strongly this user identity is identified.",
                verbose_name="Assurance level",
            ),
        ),
    ]
