# Generated by Django 4.2.9 on 2024-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0017_alter_identity_assurance_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="value",
            field=models.CharField(max_length=4000, verbose_name="Identifier value"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="uid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="User identifier"),
        ),
    ]
