# Generated by Django 4.2.5 on 2023-09-14 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Role name")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="Membership start date")),
                ("expiring_date", models.DateField(verbose_name="Membership expiring date")),
                ("identity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="identity.identity")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="role.role")),
            ],
        ),
    ]
