# Generated by Django 4.2.5 on 2023-10-17 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_attributetype_alter_identity_user_attribute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="expiring_date",
        ),
        migrations.AddField(
            model_name="membership",
            name="approver",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="expire_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Membership expire date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="approvers",
            field=models.ManyToManyField(
                blank=True, related_name="role_approvers", to="auth.group", verbose_name="Approver groups"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="inviters",
            field=models.ManyToManyField(
                blank=True, related_name="role_inviters", to="auth.group", verbose_name="Inviter groups"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="maximum_duration",
            field=models.IntegerField(default=1, verbose_name="Maximum duration (days)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="parent",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="role.role"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Role name"),
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Permission name")),
                ("cost", models.IntegerField(verbose_name="Permission cost")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "requirements",
                    models.ManyToManyField(blank=True, to="identity.attributetype", verbose_name="Requirements"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="role.permission", verbose_name="Permissions"),
        ),
    ]
