# Generated by Django 4.2.5 on 2023-10-30 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("role", "0002_remove_membership_expiring_date_membership_approver_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "Membership", "verbose_name_plural": "Memberships"},
        ),
        migrations.AlterModelOptions(
            name="permission",
            options={"verbose_name": "Permission", "verbose_name_plural": "Permissions"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="name",
            new_name="identifier",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="name",
            new_name="identifier",
        ),
        migrations.AlterField(
            model_name="permission",
            name="identifier",
            field=models.CharField(max_length=20, unique=True, verbose_name="Permission identifier"),
        ),
        migrations.AlterField(
            model_name="role",
            name="identifier",
            field=models.CharField(max_length=20, unique=True, verbose_name="Role identifier"),
        ),
        migrations.AddField(
            model_name="membership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="membership",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_inviter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="reason",
            field=models.TextField(default="", verbose_name="Membership reason"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("require", "Waiting requirements"),
                    ("approval", "Waiting approval"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                ],
                default="",
                max_length=10,
                verbose_name="Membership status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="permission",
            name="description_en",
            field=models.CharField(default="", max_length=255, verbose_name="Permission description (en)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="description_fi",
            field=models.CharField(default="", max_length=255, verbose_name="Permission description (fi)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="description_sv",
            field=models.CharField(default="", max_length=255, verbose_name="Permission description (sv)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="name_en",
            field=models.CharField(default="", max_length=50, verbose_name="Permission name (en)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="name_fi",
            field=models.CharField(default="", max_length=50, verbose_name="Permission name (fi)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="name_sv",
            field=models.CharField(default="", max_length=50, verbose_name="Permission name (sv)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.CharField(default="", max_length=255, verbose_name="Role description (en)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="description_fi",
            field=models.CharField(default="", max_length=255, verbose_name="Role description (fi)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="description_sv",
            field=models.CharField(default="", max_length=255, verbose_name="Role description (sv)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="iam_group",
            field=models.CharField(blank=True, max_length=20, verbose_name="IAM Group"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_en",
            field=models.CharField(default="", max_length=50, verbose_name="Role name (en)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="name_fi",
            field=models.CharField(default="", max_length=50, verbose_name="Role name (fi)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="name_sv",
            field=models.CharField(default="", max_length=50, verbose_name="Role name (sv)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="organisation_unit",
            field=models.CharField(default="", max_length=20, verbose_name="Organisation unit"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membership",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
