# Generated by Django 4.2.5 on 2023-11-03 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0003_alter_membership_options_alter_permission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["role__identifier", "expire_date"],
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="permission",
            options={"ordering": ["identifier"], "verbose_name": "Permission", "verbose_name_plural": "Permissions"},
        ),
    ]
