# Generated by Django 4.2.5 on 2023-11-09 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0004_alter_membership_options_alter_permission_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="requirements",
        ),
    ]
