# Generated by Django 4.2.5 on 2023-12-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0007_nationality_alter_identity_options_and_more"),
        ("role", "0005_remove_permission_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="invite_email_address",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Invite email address"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="identity",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="identity.identity"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("require", "Waiting requirements"),
                    ("approval", "Waiting approval"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                ],
                max_length=10,
                verbose_name="Membership status",
            ),
        ),
    ]
