# Generated by Django 4.2.5 on 2024-01-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0006_membership_invite_email_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="purge_delay",
            field=models.IntegerField(
                blank=True,
                help_text="Grace period from membership expiration to purge (days)",
                null=True,
                verbose_name="Purge delay (days)",
            ),
        ),
    ]
