# Generated by Django 4.2.5 on 2024-01-19 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0007_role_purge_delay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "permissions": [("search_roles", "Can search roles")],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
    ]
