# Generated by Django 4.2.5 on 2023-11-29 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0007_nationality_alter_identity_options_and_more"),
        ("role", "0005_remove_permission_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("emailverification", "E-mail verification token"),
                            ("smsverification", "SMS verification token"),
                            ("emaillogin", "E-mail login token"),
                            ("smslogin", "SMS login token"),
                            ("invite", "Invite token"),
                        ],
                        max_length=17,
                        verbose_name="Token type",
                    ),
                ),
                ("hash", models.CharField(max_length=128, verbose_name="Salt and a hashed token")),
                ("tries_left", models.SmallIntegerField(verbose_name="Number of tries left")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                (
                    "email",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="identity.emailaddress"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="role.membership"),
                ),
                (
                    "phone",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="identity.phonenumber"
                    ),
                ),
            ],
            options={
                "verbose_name": "Login token",
                "verbose_name_plural": "Login tokens",
            },
        ),
    ]
