# Generated by Django 4.2.5 on 2023-12-19 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="email",
            new_name="email_object",
        ),
        migrations.RenameField(
            model_name="token",
            old_name="phone",
            new_name="phone_object",
        ),
        migrations.AddField(
            model_name="token",
            name="email_address",
            field=models.CharField(
                blank=True,
                max_length=320,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email address",
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("emaillogin", "E-mail login token"),
                    ("phonelogin", "SMS login token"),
                    ("emailobjectverif", "E-mail object verification token"),
                    ("phoneobjectverif", "Phone object verification token"),
                    ("emailaddrverif", "E-mail address verification token"),
                    ("phonenumberverif", "Phone number verification token"),
                    ("invite", "Invite token"),
                ],
                max_length=17,
                verbose_name="Token type",
            ),
        ),
    ]
